export const letters = `TO HIS SISTER. STEAMER ”ALEXANDR NEVSKY 23,” April, 1890, early in the morning.
My dear Tunguses!
Did you have rain when Ivan was coming back from the monastery? In Yaroslavl there was such a downpour that I had to swathe myself in my leather chiton. My first impression of the Volga was poisoned by the rain, by the tear-stained windows of the cabin, and the wet nose of G., who came to meet me at the station. In the rain Yaroslavl looks like Zvenigorod, and its churches remind me of Perervinsky Monastery; there are lots of illiterate signboards, it’s muddy, jackdaws with big heads strut about the pavement.
In the steamer I made it my first duty to indulge my talent–that is, to sleep. When I woke
I beheld the sun. The Volga is not bad; water meadows, monasteries bathed in sunshine, white churches; the wide expanse is marvellous, wherever one looks it would be a nice place to sit down and begin fishing. Class ladies [Translator’s Note: I.e., School chaperons, whose duty
it is to sit in the classroom while the girls are receiving instruction from a master.] wander about on the banks, nipping at the green grass. The shepherd’s horn can be heard now and then. White gulls, looking like the younger Drishka, hover over the water.
The steamer is not up to much....
*****
Kundasova is travelling with me. Where she is going and with what object I don’t know. When I question her about it, she launches off into extremely misty allusions about someone who has appointed a tryst with her in a ravine near Kineshma, then goes off into a wild giggle and begins stamping her feet or prodding with her elbow whatever comes first. We have passed both Kineshma and the ravine, but she still goes on in the steamer, at which of course I am very much pleased; by the way, yesterday for the first time in my life I saw her eating. She eats no less than other people, but she eats mechanically, as though she were munching oats.
Kostroma is a nice town. I saw the stretch of river on which the languid Levitan used to live. I saw Kineshma, where I walked along the boulevard and watched the local -beaus-. Here I went into the chemist’s shop to buy some Bertholet salts for my tongue, which was like leather after the medicine I had taken. The chemist, on seeing Olga Petrovna, was overcome with delight and confusion; she was the same. They were evidently old acquaintances, and judging from the conversation between them they had walked more than once about the ravines near Kineshma.
... It’s rather cold and rather dull, but interesting on the whole. The steamer whistles every minute; its whistle is midway between the bray of an ass and an Aeolian harp. In five or six hours we shall be in Nizhni. The sun is rising. I slept last night artistically. My money is safe; that is because I am constantly pressing my hands on my stomach.
Very beautiful are the steam-tugs, dragging after them four or five barges each; they look like some fine young intellectual trying to run away while a plebeian wife, mother-in-law, sisterin-law, and wife’s grandmother hold on to his coat-tails.
*****
The sun is hiding behind the clouds, the sky is overcast, and the broad Volga looks gloomy. Levitan ought not to live on the Volga. It lays a weight of gloom on the soul. Though it would not be bad to have an estate on its banks.
*****
If the waiter would wake I should ask him for some coffee; as it is, I have to drink water without any relish for it. My greetings to Maryushka and Olga. [Footnote: The Chekhovs’ servants.]
Well, keep well and take care of yourselves. I will write regularly.
Your bored Volga-travelling Homo Sachalien-sis, A. CHEKHOV.
April 29, 1890.
MY DEAR TUNGUSES!
The Kama is a very dull river. To realise its beauties one would have to be a native sitting motionless on a barge beside a barrel of naphtha, or a sack of dried fish, continually taking a pull at the bottle. The river banks are bare, the trees are bare, the earth is a dull brown, there are patches of snow, and there is such a wind that the devil himself could not blow as keenly and hatefully. When a cold wind blows and ruffles up the water, which now after the floods is the colour of coffee slops, one feels cold and bored and miserable; the strains of a concertina on the bank sound dejected, figures in tattered sheepskins standing motionless on the barges that meet us look as though they were petrified by some unending grief. The towns on the Kama are grey; one would think the inhabitants were employed in the manufacture of clouds, boredom, soaking fences and mud in the streets, as their sole occupation. The stopping-places are thronged with inhabitants of the educated class, for whom the arrival of a steamer is an event....
... To judge from appearances not one of them earns more than thirty-five roubles, and all of them are ailing in some way.
I have told you already there are some legal gentlemen in the steamer: the president of the court, one of the judges, and the prosecutor. The president is a hale and hearty old German who has embraced Orthodoxy, is pious, a homoeopath, and evidently a devotee of the sex. The judge is an old man such as dear Nikolay used to draw; he walks bent double, coughs, and is fond of facetious subjects. The prosecutor is a man of forty-three, dissatisfied with life, a liberal, a sceptic, and a very good-natured fellow. All the journey these gentlemen have been occupied in eating, settling mighty questions and eating, reading and eating. There is a library on the steamer, and I saw the prosecutor reading my ”In the Twilight.” They began talking about me. Mamin-Sibiryak, who has described the Urals, is the author most liked in these parts. He is more talked of than Tolstoy.
I have been two and a half years sailing to Perm, so it seems to me. We reached there at two o’clock in the night. The train went at six o’clock in the evening. I had to wait. It rained. Rain, cold, mud ... brrr! The Uralsky line is a good one.... That is due to the abundance of business-like people here, factories, mines, and so on, for whom time is precious.
Waking yesterday morning and looking out of the carriage window I felt an aversion for nature: the earth was white, trees covered with hoar-frost, and a regular blizzard pursuing the train. Now isn’t it revolting? Isn’t it disgusting? ... I have no goloshes, I pulled on my big boots, and on my way to the refreshment-room for coffee I made the whole Ural region smell of tar. And when we got to Ekaterinburg there was rain, snow, and hail. I put on my leather coat. The cabs are something inconceivable, wretched, dirty, drenched, without springs, the horse’s four legs straddling, huge hoofs, gaunt spines ... the droshkies here are a clumsy parody of our britchkas. A tattered top is put on to a britchka, that is all. And the more exactly I describe the cabman here and his vehicle, the more it will seem like a caricature. They drive not on the middle of the road where it is jolting, but near the gutter where it is muddy and soft. All the cabmen are like Dobrolyubov.
In Russia all the towns are alike. Ekaterinburg is exactly the same as Perm or Tula. The note of the bells is magnificent, velvety. I stopped at the American Hotel (not at all bad), and at once sent word of my arrival to A. M. S., telling him I meant to stay in my hotel room for two days.
The people here inspire the newcomer with a feeling akin to horror. They are big-browed, big-jawed, broad-shouldered fellows with huge fists and tiny eyes. They are born in the local iron foundries, and at their birth a mechanic officiates instead of an accoucheur. A specimen comes into your room with a samovar or a bottle of water, and you expect him every minute to murder you. I stand aside. This morning just such a one came in, big-browed, big-jawed, huge, towering up to the ceiling, seven feet across the shoulders and wearing a fur coat too.
Well, I thought, this one will certainly murder me. It appeared that this was our relation A. M. S. We began to talk. He is a member of the local Zemstvo and manager of his cousin’s mill, which is lighted by electric light; he is editor of the -Ekaterinburg Weekwhich is under the censorship of the police-master Baron Taube, is married and has two children, is growing rich and getting fat and elderly, and lives in a ”substantial way.” He says he has no time to be bored. He advised me to visit the museum, the factories, and the mines; I thanked him for his advice. He invited me to tea to-morrow evening; I invited him to dine with me. He did not invite me to dinner, and altogether did not press me very much to visit him. From this mother may conclude that the relations’ heart is not softened.... Relations are a race in which I take no interest.
There is snow in the street, and I have purposely let down the blind over the windows so as not to see the Asiatic sight. I am sitting here waiting for an answer from Tyumen to my telegram. I telegraphed: ”Tyumen. Kurbatov steamer line. Reply paid. Inform me when the passenger steamer starts Tomsk.” It depends on the answer whether I go by steamer or gallop fifteen hundred versts in the slush of the thaw.
All night long they beat on sheets of iron at every corner here. You need a head of iron not to go crazy from the incessant clanging. To-day I tried to make myself coffee. The result was a horrid mess. I just drank it with a shrug. I looked at five sheets, handled them, and did not take one. I am going to-day to buy rubber overshoes.
*****
Shall I find a letter from you at Irkutsk? Ask Lika not to leave such big margins in her letters.
Your Homo Sachaliensis, A. CHEKHOV.
TO HIS SISTER. KRASNOYARSK, May 28, 1890.
What a deadly road! It was all we could do to crawl to Krasnoyarsk and my trap had to be repaired twice. The first thing to be broken was the vertical piece of iron connecting the front of the carriage with the axle; then the so-called circle under the front broke. I have never in all my life seen such a road–such impassable mud and such an utterly neglected road. I am going to write about its horrors to the -Novoye
Vremya-, and so won’t talk about it now.
The last three stations have been splendid; as one comes down to Krasnoyarsk one seems to be getting into a different world. You come out of the forest into a plain which is like our Donets steppe, but here the mountain ridges are grander. The sun shines its very best and the birch-trees are out, though three stations back the buds were not even bursting. Thank God, I have at last reached a summer in which there is neither rain nor a cold wind. Krasnoyarsk is a picturesque, cultured town; compared with it, Tomsk is ”a pig in a skull-cap and the acme of -mauvais ton-.” The streets are clean and paved, the houses are of stone and large, the churches are elegant.
I am alive and perfectly well. My money is all right, and so are my things; I lost my woollen stockings but soon found them again.
Apart from my trap, everything so far has been satisfactory and I have nothing to complain of. Only I am spending an awful lot of money. Incompetence in the practical affairs of life is never felt so much as on a journey. I pay more than I need to, I do the wrong thing, and I say the wrong thing, and I am always expecting what does not happen.
... I shall be in Irkutsk in five or six days, shall spend as many days there, then drive on to Sryetensk–and that will be the end of my journey on land. For more than a fortnight I have been driving without a break, I think about nothing else, I live for nothing else; every morning I see the sunrise from beginning to end. I’ve grown so used to it that it seems as though all my life I had been driving and struggling with the muddy roads. When it does not rain, and there are no pits of mud on the road, one feels queer and even a little bored. And how filthy I am, what a rapscallion I look! What a state my luckless clothes are in!
... For mother’s information: I have still a jar and a half of coffee; I feed on locusts and wild honey; I shall dine to-day at Irkutsk. The further east one gets the dearer everything is. Rye flour is seventy kopecks a -pood-, while on the other side of Tomsk it was twenty-five and twenty-seven kopecks per -pood-, and wheaten flour thirty kopecks. The tobacco sold in Siberia is vile and loathsome; I tremble because mine is nearly done.
... I am travelling with two lieutenants and an army doctor who are all on their way to the Amur. So my revolver is after all quite superfluous. In such company hell would have no terrors. We are just having tea at the station, and after tea we are going to have a look at the town.
I should have no objection to living in Krasnoyarsk. I can’t think why this is a favourite place for sending exiles to.
*****
Your Homo Sachaliensis, A. CHEKHOV.
TO HIS BROTHER ALEXANDR. IRKUTSK, June
5, 1890. MY EUROPEAN BROTHER,
It is, of course, unpleasant to live in Siberia; but better to live in Siberia and feel oneself a man of moral worth, than to live in Petersburg
with the reputation of a drunkard and a scoundrel. No reference to present company.
*****
Siberia is a cold and long country. I drive on and on and see no end to it. I see little that is new or of interest, but I feel and experience a great deal. I have contended with flooded rivers, with cold, with impassable mud, hunger and sleepiness: such sensations as you could not get for a million in Moscow! You ought to come to Siberia. Ask the authorities to exile you.
The best of all Siberian towns is Irkutsk. Tomskis not worth a brass farthing, and the district towns are no better than the Kryepkaya in which you were so heedlessly born. What is most provoking, there is nothing to eat in the district towns, and oh dear, how conscious one is of that on the journey! You get to a town and feel ready to eat a mountain; you arrive and– alack!–no sausage, no cheese, no meat, no herring even, but the same insipid eggs and milk as in the villages.
On the whole I am satisfied with my expedition, and don’t regret having come. The travelling is hard, but the resting after it is delightful. I rest with enjoyment.
From Irkutsk I shall make for Baikal, which
I shall cross by steamer; it’s a thousand versts from the Baikal to the Amur, and thence I shall go by steamer to the Pacific, where the first thing I shall do is to have a bath and eat oysters.
I got here yesterday and went first of all to have a bath, then to bed. Oh, how I slept! I never understood what sleep meant till now.
*****
I bless you with both hands.
Your Asiatic brother, A. CHEKHOV.
STATION LISTVENITCHNAYA, ON LAKE BAIKAL, June 13.
I am having an idiotic time. On the evening of the 11th of June, the day before yesterday, we set off from Irkutsk, in the fond hope of catching the Baikal steamer, which leaves at four o’clock in the morning. From Irkutsk to Baikal there are only three stations. At the first station they informed us that all the horses were exhausted and that it was therefore impossible to go. We had to put up for the night. Yesterday morning we set off from that station, and by midday we reached Baikal. We went to the harbour, and in answer to our inquiries were told that the steamer did not go till Friday the fifteenth. This meant that we should have to sit on the bank and look at the water and wait. As there is nothing that does not end in time, I have no objection to waiting, and always wait patiently; but the point is the steamer leaves Sryetensk on the 20th and sails down the Amur: if we don’t catch it we must wait for the next steamer, which does not go till the 30th. Merciful Heavens, when shall I get to Sahalin!
We drove to Baikal along the bank of the Angara, which rises out of Lake Baikal and flows into the Yenissey. Look at the map. The banks are picturesque. Mountains and mountains, and dense forests on the mountains. The weather was exquisite still, sunny and warm; as I drove
I felt I was exceptionally well; I felt so happy that I cannot describe it. It was perhaps the contrast after the stay at Irkutsk, and because the scenery on the Angara is like Switzerland. It is something new and original. We drove along the river bank, came to the mouth of the river, and turned to the left; then we came upon the bank of Lake Baikal, which in Siberia is called the sea. It is like a mirror. The other side, of course, is out of sight; it is ninety versts away. The banks are high, steep, stony, and covered with forest, to right and to left there are promontories which jut into the sea like Audag or the Tohtebel at Feodosia. It’s like the Crimea. The station of Listvenitchnaya lies at the water’s edge, and is strikingly like Yalta: if the houses were white it would be exactly like Yalta. Only there are no buildings on the mountains, as they are too overhanging and it is impossible to build on them.
We have taken a little barn of a lodging that reminds one of any of the Kraskovsky summer villas. Just outside the window, two or three yards from the wall, is Lake Baikal. We pay a rouble a day. The mountains, the forests, the mirror-like Baikal are all poisoned for me by the thought that we shall have to stay here till the fifteenth. What are we to do here? What is more, we don’t know what there is for us to eat. The inhabitants feed upon nothing but garlic. There is neither meat nor fish. They have given us no milk, but have promised it. For a little white loaf they demanded sixteen kopecks. I bought some buckwheat and a piece of smoked pork, and asked them to make a thin porridge of it: it was not nice, but there was nothing to be done, I had to eat it. All the evening we hunted about the village to find someone who would sell us a hen, and found no one.... But there is vodka. The Russian is a great pig. If you ask him why he doesn’t eat meat and fish he justifies himself by the absence of transport, ways and communications, and so on, and yet vodka is to be found in the remotest villages and as much of it as you please. And yet one would have supposed that it would have been much easier to obtain meat and fish than vodka, which is more expensive and more difficult to transport.... Yes, drinking vodka must be much more interesting than fishing in Lake Baikal or rearing cattle.
At midnight a little steamer arrived; we went to look at it, and seized the opportunity to ask if there was anything to eat. We were told that to-morrow we should be able to get dinner, but that now it was late, the kitchen fire was out, and so on. We thanked them for ”to-morrow”–it was something to look forward to anyway! But alas! the captain came in and told us that at four o’clock in the morning the steamer was setting off for Kultuk. We thanked him. In the refreshment bar, where there was not room to turn round, we drank a bottle of sour beer (thirty-five kopecks), and saw on a plate some amber beads–it was salmon caviare. We returned home, and to sleep. I am sick of sleeping. Every day one has to put down one’s sheepskin with the wool upwards, under one’s head one puts a folded greatcoat and a pillow, and one sleeps on this heap in one’s waistcoat and trousers.... Civilization, where art thou?
To-day there is rain and Lake Baikal is plunged in mist. ”Interesting,” Semaskho would say. It’s dull. One ought to sit down and write, but one can never work in bad weather. One has a foreboding of merciless boredom; if I were alone I should not mind but there are two lieutenants and an army doctor with me, who are fond of talking and arguing. They don’t understand much but they talk about everything. One of the lieutenants, moreover, is a bit of a Hlestakov and a braggart. When one is travelling one absolutely must be alone. To sit in a chaise or in a room alone with one’s thoughts is much more interesting than being with people.
*****
Congratulate me: I sold my own carriage at Irkutsk. How much I gained on it I won’t say, or mother would fall into a faint and not sleep for five nights.
Your Homo Sachaliensis, A. CHEKHOV.
`;
